import { FormattedMessage } from 'react-intl';

export const GOBI_MAPPING_TYPES = {
  default: 'Default',
  custom: 'Custom',
};

export const FORMATTED_ORDER_MAPPING_TYPES = {
  ListedElectronicMonograph: <FormattedMessage id="ui-gobi-settings.order.mappings.type.listedElectronicMonograph" />,
  ListedElectronicSerial: <FormattedMessage id="ui-gobi-settings.order.mappings.type.listedElectronicSerial" />,
  ListedPrintMonograph: <FormattedMessage id="ui-gobi-settings.order.mappings.type.listedPrintMonograph" />,
  ListedPrintSerial: <FormattedMessage id="ui-gobi-settings.order.mappings.type.listedPrintSerial" />,
  UnlistedPrintMonograph: <FormattedMessage id="ui-gobi-settings.order.mappings.type.unlistedPrintMonograph" />,
  UnlistedPrintSerial: <FormattedMessage id="ui-gobi-settings.order.mappings.type.unlistedPrintSerial" />,
};

export const FORMATTED_TRANSLATORS = {
  lookupContributorNameTypeId: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupContributorNameTypeId" />,
  lookupExpenseClassId: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupExpenseClassId" />,
  lookupAcquisitionMethodIds: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupAcquisitionMethodIds" />,
  lookupAcquisitionUnitDefaultAcqUnitName: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupAcquisitionUnitDefaultAcqUnitName" />,
  lookupLocationId: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupLocationId" />,
  lookupMaterialTypeId: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupMaterialTypeId" />,
  lookupFundId: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupFundId" />,
  lookupMock: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupMock" />,
  lookupOrganization: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupOrganization" />,
  lookupProductIdType: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupProductIdType" />,
  lookupBillTo: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupBillTo" />,
  lookupShipTo: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupShipTo" />,
  lookupSuffix: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupSuffix" />,
  lookupPrefix: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupPrefix" />,
  lookupLinkedPackage: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupLinkedPackage" />,
  lookupConfigAddress: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.lookupConfigAddress" />,
  separateISBNQualifier: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.separateISBNQualifier" />,
  truncateISBNQualifier: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.truncateISBNQualifier" />,
  toBoolean: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.toBoolean" />,
  toDate: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.toDate" />,
  toDouble: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.toDouble" />,
  toInteger: <FormattedMessage id="ui-gobi-settings.order.mappings.translator.toInteger" />,
};

export const FIELDS = {
  ACCESS_PROVIDER: 'ACCESS_PROVIDER',
  ACQUISITION_METHOD: 'ACQUISITION_METHOD',
  LOOKUP_ACQUISITION_UNIT_DEFAULT_ACQ_UNIT_NAME: 'LOOKUP_ACQUISITION_UNIT_DEFAULT_ACQ_UNIT_NAME',
  LOOKUP_ACQUISITION_UNIT_BY_VENDOR_ACC_NUMBER: 'LOOKUP_ACQUISITION_UNIT_BY_VENDOR_ACC_NUMBER',
  ACTIVATED: 'ACTIVATED',
  ACTIVATION_DUE: 'ACTIVATION_DUE',
  ADDITIONAL_COST: 'ADDITIONAL_COST',
  AGGREMENT_ID: 'AGGREMENT_ID',
  ALERTS: 'ALERTS',
  APPROVED: 'APPROVED',
  ASSIGNED_TO: 'ASSIGNED_TO',
  BILL_TO: 'BILL_TO',
  CANCELLATION_RESTRICTION: 'CANCELLATION_RESTRICTION',
  CANCELLATION_RESTRICTION_NOTE: 'CANCELLATION_RESTRICTION_NOTE',
  CLAIMED: 'CLAIMED',
  CLAIM_GRACE: 'CLAIM_GRACE',
  CLAIM_SENT: 'CLAIM_SENT',
  COLLECTION: 'COLLECTION',
  CONTRIBUTOR: 'CONTRIBUTOR',
  CONTRIBUTOR_NAME_TYPE: 'CONTRIBUTOR_NAME_TYPE',
  CREATE_INVENTORY: 'CREATE_INVENTORY',
  CURRENCY: 'CURRENCY',
  DATE_ORDERED: 'DATE_ORDERED',
  DESCRIPTION: 'DESCRIPTION',
  DISCOUNT: 'DISCOUNT',
  DISCOUNT_TYPE: 'DISCOUNT_TYPE',
  DONOR: 'DONOR',
  EDITION: 'EDITION',
  ENCUMBRANCE: 'ENCUMBRANCE',
  EXCHANGE_RATE: 'EXCHANGE_RATE',
  EXPECTED_ACTIVATION: 'EXPECTED_ACTIVATION',
  EXPECTED_RECEIPT_DATE: 'EXPECTED_RECEIPT_DATE',
  EXPENSE_CLASS: 'EXPENSE_CLASS',
  FUND_ID: 'FUND_ID',
  FUND_CODE: 'FUND_CODE',
  FUND_PERCENTAGE: 'FUND_PERCENTAGE',
  LICENSE_CODE: 'LICENSE_CODE',
  LICENSE_DESCRIPTION: 'LICENSE_DESCRIPTION',
  LICENSE_REFERENCE: 'LICENSE_REFERENCE',
  LINKED_PACKAGE: 'LINKED_PACKAGE',
  LIST_UNIT_PRICE: 'LIST_UNIT_PRICE',
  LIST_UNIT_PRICE_ELECTRONIC: 'LIST_UNIT_PRICE_ELECTRONIC',
  LOCATION: 'LOCATION',
  MANUAL_PO: 'MANUAL_PO',
  MATERIAL_SUPPLIER: 'MATERIAL_SUPPLIER',
  MATERIAL_TYPE: 'MATERIAL_TYPE',
  NOTES: 'NOTES',
  NOTE_FROM_VENDOR: 'NOTE_FROM_VENDOR',
  ORDER_TYPE: 'ORDER_TYPE',
  PACKAGE_DESIGNATION: 'PACKAGE_DESIGNATION',
  PO_LINE_DESCRIPTION: 'PO_LINE_DESCRIPTION',
  PO_LINE_ESTIMATED_PRICE: 'PO_LINE_ESTIMATED_PRICE',
  PO_LINE_ORDER_FORMAT: 'PO_LINE_ORDER_FORMAT',
  PO_LINE_PAYMENT_STATUS: 'PO_LINE_PAYMENT_STATUS',
  PO_LINE_RECEIPT_STATUS: 'PO_LINE_RECEIPT_STATUS',
  PREFIX: 'PREFIX',
  PRODUCT_ID: 'PRODUCT_ID',
  PRODUCT_ID_TYPE: 'PRODUCT_ID_TYPE',
  PRODUCT_QUALIFIER: 'PRODUCT_QUALIFIER',
  PUBLICATION_DATE: 'PUBLICATION_DATE',
  PUBLISHER: 'PUBLISHER',
  PURCHASE_ORDER_ID: 'PURCHASE_ORDER_ID',
  QUANTITY_ELECTRONIC: 'QUANTITY_ELECTRONIC',
  QUANTITY_PHYSICAL: 'QUANTITY_PHYSICAL',
  RECEIPT_DATE: 'RECEIPT_DATE',
  RECEIPT_DUE: 'RECEIPT_DUE',
  RECEIVING_NOTE: 'RECEIVING_NOTE',
  ONGOING_IS_SUBSCRIPTION: 'ONGOING_IS_SUBSCRIPTION',
  ONGOING_DATE: 'ONGOING_DATE',
  ONGOING_INTERVAL: 'ONGOING_INTERVAL',
  ONGOING_MANUAL: 'ONGOING_MANUAL',
  ONGOING_REVIEW_PERIOD: 'ONGOING_REVIEW_PERIOD',
  ONGOING_NOTES: 'ONGOING_NOTES',
  ONGOING_REVIEW_DATE: 'ONGOING_REVIEW_DATE',
  RECEIVING_WORKFLOW: 'RECEIVING_WORKFLOW',
  REPORTING_CODE: 'REPORTING_CODE',
  REPORTING_DESCRIPTION: 'REPORTING_DESCRIPTION',
  REQUESTER: 'REQUESTER',
  RE_ENCUMBER: 'RE_ENCUMBER',
  RUSH: 'RUSH',
  SELECTOR: 'SELECTOR',
  SHIP_TO: 'SHIP_TO',
  SOURCE: 'SOURCE',
  SUBSCRIPTION_FROM: 'SUBSCRIPTION_FROM',
  SUBSCRIPTION_INTERVAL: 'SUBSCRIPTION_INTERVAL',
  SUBSCRIPTION_TO: 'SUBSCRIPTION_TO',
  SUFFIX: 'SUFFIX',
  TAGS: 'TAGS',
  TITLE: 'TITLE',
  TOTAL_ESTIMATED_PRICE: 'TOTAL_ESTIMATED_PRICE',
  TOTAL_ITEMS: 'TOTAL_ITEMS',
  TRIAL: 'TRIAL',
  USER_LIMIT: 'USER_LIMIT',
  URL: 'URL',
  VENDOR: 'VENDOR',
  VENDOR_ACCOUNT: 'VENDOR_ACCOUNT',
  VENDOR_INSTRUCTIONS: 'VENDOR_INSTRUCTIONS',
  VENDOR_REF_NO: 'VENDOR_REF_NO',
  VENDOR_REF_NO_TYPE: 'VENDOR_REF_NO_TYPE',
  VOLUMES: 'VOLUMES',
  WORKFLOW_STATUS: 'WORKFLOW_STATUS',
};
